# Generated by Django 6.0 on 2026-03-23 13:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('push', 'Push Notification')], default='email', max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_successful', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='expenses.debt')),
            ],
            options={
                'db_table': 'reminder_logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
