import uuid
from django.db import models
from django.conf import settings


class MonthlyReport(models.Model):
    """
    Pre-computed monthly expense report per user per group.
    Generated by Celery task on the 1st of each month.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="monthly_reports",
    )
    group = models.ForeignKey(
        "groups.Group",
        on_delete=models.CASCADE,
        related_name="monthly_reports",
    )
    year = models.PositiveSmallIntegerField()
    month = models.PositiveSmallIntegerField()  # 1–12

    total_spent = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    total_paid = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    total_owed = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    total_received = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    expense_count = models.PositiveIntegerField(default=0)

    # JSON snapshot of category breakdown: {"food": 1500.00, "transport": 300.00}
    category_breakdown = models.JSONField(default=dict)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "monthly_reports"
        unique_together = [("user", "group", "year", "month")]
        ordering = ["-year", "-month"]

    def __str__(self):
        return f"Report: {self.user} | {self.group} | {self.year}-{self.month:02d}"
