# Generated by Django 6.0 on 2026-04-02 21:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_initial'),
        ('payments', '0002_initial'),
        ('users', '0006_alter_accountdetails_account_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransferPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('disputed', 'Disputed')], default='pending', max_length=10)),
                ('note', models.TextField(blank=True, default='')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_payments', to='users.accountdetails')),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transfers_received', to=settings.AUTH_USER_MODEL)),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transfer_payments', to='expenses.debt')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transfers_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bank_transfer_payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
