# Generated by Django 6.0 on 2026-04-01 21:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid3, editable=False, primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=255)),
                ('account_number', models.IntegerField(max_length=25)),
                ('bank_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'account_details',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='account_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account_details', to='users.accountdetails'),
        ),
    ]
