# Generated by Django 6.0 on 2026-04-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_accountdetails_user_account_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='account_number',
            field=models.IntegerField(),
        ),
    ]
