# Generated by Django 6.0 on 2026-04-01 21:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_accountdetails_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
