# Generated by Django 6.0 on 2026-04-01 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_accountdetails_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_details',
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_details_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
