# Generated by Django 6.0 on 2026-04-02 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_account_details_accountdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='account_number',
            field=models.CharField(max_length=15),
        ),
    ]
