# Generated by Django 6.0 on 2026-03-23 13:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_owed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_received', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expense_count', models.PositiveIntegerField(default=0)),
                ('category_breakdown', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='groups.group')),
            ],
            options={
                'db_table': 'monthly_reports',
                'ordering': ['-year', '-month'],
            },
        ),
    ]
